export const day=(offset=0)=>{const d=new Date();d.setHours(12,0,0,0);d.setDate(d.getDate()+offset);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
export function rating(reviews,now=day()) { const eligible=reviews.filter(r=>r.date<=now&&Number.isFinite(r.score)&&r.score>=1&&r.score<=5);const today=eligible.filter(r=>r.date===now);const sample=today.length?today:eligible.filter(r=>(Date.parse(now)-Date.parse(r.date))/86400000<=30);return{score:sample.length?sample.reduce((a,r)=>a+r.score,0)/sample.length:null,count:sample.length,period:today.length?'today':'30days',last:sample.map(r=>r.date).sort().at(-1)||null}; }
export function confirmAdd(cart,product,quantity,confirmed){if(confirmed!==true)throw new Error('confirmation_required');if(!product)throw new Error('unknown_product');if(!Number.isInteger(quantity)||quantity<1)throw new Error('invalid_quantity');const already=cart[product.id]||0;if(already+quantity>product.stock)throw new Error('insufficient_stock');return{...cart,[product.id]:already+quantity};}
export function analogs(product,products){return products.filter(p=>p.id!==product.id&&p.stock>0&&p.compat===product.compat).sort((a,b)=>a.price-b.price);}
export function findProducts(query,products){const q=query.toLowerCase().replace(/с(?=\d)/g,'c');const sku=q.match(/demo[- ]?\d{3}/)?.[0].replace(' ','-');if(sku)return products.filter(p=>p.id.toLowerCase()===sku);let subset=products;const type=/кабел|cable|сым/.test(q)?'cable':/розет|socket/.test(q)?'socket':/ламп|свет|led|шам|light/.test(q)?'light':/автомат|breaker|c16|c25|c10/.test(q)?'breaker':null;if(type)subset=subset.filter(p=>p.category===type);const amp=q.match(/c(\d+)/)?.[1];if(amp)subset=subset.filter(p=>p.amps===Number(amp));const budget=q.match(/(?:до|under|дейін|бюджет)\s*(\d[\d ]*)/i)?.[1]?.replaceAll(' ','');if(budget)subset=subset.filter(p=>p.price<=Number(budget));return type||amp||budget?subset:products.filter(p=>Object.values(p.name).join(' ').toLowerCase().includes(q)||p.id.toLowerCase().includes(q));}
const seedReviews=(scores)=>scores.map((score,i)=>({score,date:day(-1-i*3),author:['Алексей','Дана','Ерлан'][i%3],text:[{ru:'Удобно устанавливать. Характеристики соответствуют описанию.',kk:'Орнату ыңғайлы. Сипаттамалары мәліметке сәйкес.',en:'Easy to install. Specifications match the description.'},{ru:'Доставили аккуратно. Для моей задачи подошёл.',kk:'Ұқыпты жеткізілді. Менің міндетіме сәйкес келді.',en:'Arrived carefully packed. Suitable for my task.'},{ru:'Хороший вариант, но стоит сравнить условия гарантии.',kk:'Жақсы нұсқа, кепілдік шарттарын салыстырған жөн.',en:'A good option. Worth comparing warranty terms.'}][i%3],synthetic:true}));
const base={source:'synthetic',updatedAt:day(),certificate:null};
export const products=[
{...base,id:'DEMO-101',name:{ru:'Автоматический выключатель C16',kk:'C16 автоматты ажыратқыш',en:'C16 miniature circuit breaker'},category:'breaker',brand:'VOLT · DEMO',code:'C16',amps:16,compat:'mcb-1p-c16-6ka',price:2450,stock:48,warehouses:[['Алматы',32],['Астана',16]],spec:{ru:'1 полюс · 16 А · 6 кА',kk:'1 полюс · 16 А · 6 кА',en:'1 pole · 16 A · 6 kA'},material:{ru:'Термостойкий пластик, медные контакты',kk:'Ыстыққа төзімді пластик, мыс түйіспелер',en:'Heat-resistant plastic, copper contacts'},origin:{ru:'Китай (демо)',kk:'Қытай (демо)',en:'China (demo)'},image:'assets/breaker.jpg',history:[2700,2550,2450],reviews:seedReviews([5,4,5])},
{...base,id:'DEMO-102',name:{ru:'Автоматический выключатель C16 Pro',kk:'C16 Pro автоматты ажыратқыш',en:'C16 Pro miniature circuit breaker'},category:'breaker',brand:'VOLT PRO · DEMO',code:'C16',amps:16,compat:'mcb-1p-c16-6ka',price:3150,stock:24,warehouses:[['Алматы',24]],spec:{ru:'1 полюс · 16 А · 6 кА',kk:'1 полюс · 16 А · 6 кА',en:'1 pole · 16 A · 6 kA'},material:{ru:'Термостойкий пластик, медные контакты',kk:'Ыстыққа төзімді пластик, мыс түйіспелер',en:'Heat-resistant plastic, copper contacts'},origin:{ru:'Турция (демо)',kk:'Түркия (демо)',en:'Türkiye (demo)'},image:'assets/breaker.jpg',history:[2900,3000,3150],reviews:seedReviews([5,5,4])},
{...base,id:'DEMO-103',name:{ru:'Автоматический выключатель C16 Basic',kk:'C16 Basic автоматты ажыратқыш',en:'C16 Basic miniature circuit breaker'},category:'breaker',brand:'VOLT BASIC · DEMO',code:'C16',amps:16,compat:'mcb-1p-c16-6ka',price:1980,stock:0,warehouses:[],arrival:day(3),spec:{ru:'1 полюс · 16 А · 6 кА',kk:'1 полюс · 16 А · 6 кА',en:'1 pole · 16 A · 6 kA'},material:{ru:'Термостойкий пластик, медные контакты',kk:'Ыстыққа төзімді пластик, мыс түйіспелер',en:'Heat-resistant plastic, copper contacts'},origin:{ru:'Китай (демо)',kk:'Қытай (демо)',en:'China (demo)'},image:'assets/breaker.jpg',history:[1850,1920,1980],reviews:seedReviews([4,4,5])},
{...base,id:'DEMO-201',name:{ru:'Кабель ВВГнг-LS 3×2,5 мм²',kk:'ВВГнг-LS 3×2,5 мм² кабелі',en:'VVGng-LS cable 3×2.5 mm²'},category:'cable',brand:'CABLE LAB · DEMO',code:'3×2,5',compat:'cable-vvg-3x2.5',price:690,stock:180,warehouses:[['Алматы',100],['Астана',80]],unit:'m',spec:{ru:'Медь · 3 жилы · 0,66 кВ',kk:'Мыс · 3 өзек · 0,66 кВ',en:'Copper · 3 cores · 0.66 kV'},material:{ru:'Медные жилы, изоляция ПВХ',kk:'Мыс өзектер, ПВХ оқшаулау',en:'Copper conductors, PVC insulation'},origin:{ru:'Казахстан (демо)',kk:'Қазақстан (демо)',en:'Kazakhstan (demo)'},image:'assets/cable.jpg',history:[640,670,690],reviews:seedReviews([5,4,4])},
{...base,id:'DEMO-104',name:{ru:'Автоматический выключатель C25',kk:'C25 автоматты ажыратқыш',en:'C25 miniature circuit breaker'},category:'breaker',brand:'VOLT · DEMO',code:'C25',amps:25,compat:'mcb-1p-c25-6ka',price:2700,stock:12,warehouses:[['Алматы',12]],spec:{ru:'1 полюс · 25 А · 6 кА',kk:'1 полюс · 25 А · 6 кА',en:'1 pole · 25 A · 6 kA'},material:{ru:'Термостойкий пластик, медные контакты',kk:'Ыстыққа төзімді пластик, мыс түйіспелер',en:'Heat-resistant plastic, copper contacts'},origin:{ru:'Китай (демо)',kk:'Қытай (демо)',en:'China (demo)'},image:'assets/breaker.jpg',history:[2800,2750,2700],reviews:seedReviews([4,5])},
{...base,id:'DEMO-301',name:{ru:'Розетка с заземлением 16 А',kk:'Жерге тұйықталған 16 А розетка',en:'Grounded wall socket 16 A'},category:'socket',brand:'HOME LAB · DEMO',code:'16A',compat:'socket-schuko-16a',price:1850,stock:35,warehouses:[['Алматы',20],['Астана',15]],spec:{ru:'250 В · IP20 · белая',kk:'250 В · IP20 · ақ',en:'250 V · IP20 · white'},material:{ru:'Пластик, латунные контакты',kk:'Пластик, жез түйіспелер',en:'Plastic, brass contacts'},origin:{ru:'Турция (демо)',kk:'Түркия (демо)',en:'Türkiye (demo)'},image:'assets/socket.jpg',history:[1850,1850,1850],reviews:seedReviews([5,5,4])},
{...base,id:'DEMO-401',name:{ru:'Светодиодная лампа 9 Вт E27',kk:'9 Вт E27 жарықдиодты шам',en:'LED bulb 9 W E27'},category:'light',brand:'LIGHT LAB · DEMO',code:'9W',compat:'led-e27-9w-4000k',price:850,stock:62,warehouses:[['Алматы',42],['Астана',20]],spec:{ru:'4000 К · 806 лм · E27',kk:'4000 К · 806 лм · E27',en:'4000 K · 806 lm · E27'},material:{ru:'Поликарбонат, алюминий',kk:'Поликарбонат, алюминий',en:'Polycarbonate, aluminium'},origin:{ru:'Китай (демо)',kk:'Қытай (демо)',en:'China (demo)'},image:'assets/bulb.jpg',history:[990,900,850],reviews:seedReviews([4,4,5])},
{...base,id:'DEMO-402',name:{ru:'Светодиодная лампа 9 Вт E27 Plus',kk:'9 Вт E27 Plus жарықдиодты шам',en:'LED bulb 9 W E27 Plus'},category:'light',brand:'LIGHT PLUS · DEMO',code:'9W',compat:'led-e27-9w-4000k',price:1100,stock:0,warehouses:[],arrival:null,spec:{ru:'4000 К · 806 лм · E27',kk:'4000 К · 806 лм · E27',en:'4000 K · 806 lm · E27'},material:{ru:'Поликарбонат, алюминий',kk:'Поликарбонат, алюминий',en:'Polycarbonate, aluminium'},origin:{ru:'Китай (демо)',kk:'Қытай (демо)',en:'China (demo)'},image:'assets/bulb.jpg',history:[1000,1050,1100],reviews:[]}
];
